server:
  port: 9002

spring:
  application:
    name: book-consumer-main

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8001/eureka/
#  instance:
#    instance-id: book-consumer-main
